### ISSUE TITLE
This method can be uploaded to the app store？

### ISSUE THREAD

**Issue by Sky-star** [dnpp73/DPSystemVolumeController#1]
Use this method can be uploaded to the app store?

**Comment by dnpp73** [comment]
Currently I don' know because never upload.
but now I'm making an app using this library, and try to upload maybe April.

**Comment by Sky-star** [comment]
Thank you very much.If the upload is successful is a nice thing.

**Comment by dnpp73** [comment]
If pass Apple's review or not, I'll update README and close this issue.
Thanks.

**Comment by dnpp73** [comment]
There is no problem. An app including this library passed the Apple's review. 
Thanks.

**Comment by saikiranSia** [comment]
Can we Hide Mute Pop Up
